### ISSUE TITLE
GIves error about  GenomeTester4/glistmaker exists but it's a binary file so i cant see what's in it.

### ISSUE THREAD

**Issue by ilkaybuysal** [bioinfo-ut/PlasmidSeeker#23] opened 2020-11-13 21:53 UTC
Hello everyone,

This is what I'm running:
perl /usr/local/PlasmidSeeker-1.0/plasmidseeker.pl -d usr/local/PlasmidSeeker-1.0/db_w20 -i MG_176020.R1.fq -b ./GCF_000014425.1_ASM1442v1_genomic.fna -o ./MG_176020_R1_results

and I'm having an error :/

Loading database...
Converting sample reads to k-mers...
Can't exec "GenomeTester4/glistmaker": No such file or directory at /usr/local/PlasmidSeeker-1.0/plasmidseeker.pl line 256.
Can't exec "GenomeTester4/glistcompare": No such file or directory at /usr/local/PlasmidSeeker-1.0/plasmidseeker.pl line 258.
Finding coverage of bacterial isolate...
Can't exec "GenomeTester4/glistmaker": No such file or directory at /usr/local/PlasmidSeeker-1.0/plasmidseeker.pl line 264.
Can't exec "GenomeTester4/glistcompare": No such file or directory at /usr/local/PlasmidSeeker-1.0/plasmidseeker.pl line 137.
Can't exec "GenomeTester4/glistcompare": No such file or directory at /usr/local/PlasmidSeeker-1.0/plasmidseeker.pl line 138.
Can't exec "GenomeTester4/gdistribution": No such file or directory at /usr/local/PlasmidSeeker-1.0/plasmidseeker.pl line 139.
Printing distribution of tmp_bacteria.txt
Initial median 0
Can't exec "GenomeTester4/glistcompare": No such file or directory at /usr/local/PlasmidSeeker-1.0/plasmidseeker.pl line 144.
Can't exec "GenomeTester4/glistcompare": No such file or directory at /usr/local/PlasmidSeeker-1.0/plasmidseeker.pl line 145.
Can't exec "GenomeTester4/gdistribution": No such file or directory at /usr/local/PlasmidSeeker-1.0/plasmidseeker.pl line 146.
FINAL median 0
Bacteria median coverage is 0
Bacteria median coverage is too low (less than 3). Higher coverage dataset is needed or use flag --ponly at /usr/local/PlasmidSeeker-1.0/plasmidseeker.pl line 268.

The file GenomeTester4/glistmaker exists but it's a binary file so i cant see what's in it.

**Comment by mihkelvaher** [comment] 2020-11-16 10:05
Hi!
The problem is not with GT4 programs but where plasmidseeker.pl looks for the binaries.

If I remember correctly, PlasmidSeeker can currently only be run in the working dir that contains plasmidseeker.pl and GenomeTester4/* making it usable only locally. Hopefully, this constraint gets resolved in the next release (date unknown).

**Comment by ilkaybuysal** [comment] 2020-11-16 10:17
Hi, thanks a lot! 

The plasmidseeker is set up just as the website said though, I'm not I understand why it cannot find the GenomeTester.
so does that mean it cannot be used via the server, or did I understand wrong?

**Comment by mihkelvaher** [comment] 2020-11-16 12:03
You can ignore my previous comment.

You were using v1.0 which had the path problems. v1.3 has been some time in master but didn't have its own release yet - now it does.

Please try v1.3 and see if the problem persists.

**Closed** 2021-04-22 06:19 UTC
